package gui;

import static dao.XuLyCSDL.getThongBao;
import dao.XuLyNhapKho;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import pojo.DanhSach;
import static pojo.DanhSach.getDanhSachNV;
import static pojo.DanhSach.getDanhSachVT;
import static pojo.DanhSach.getLichSuNK;
import pojo.NhanVien;
import pojo.NhapKho;
import pojo.VatTu;

public class FormNhapKho extends ParentForm {
    NonEditableTableModel dtmVT = new NonEditableTableModel();
    DefaultComboBoxModel<NhanVien> dcmNV = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<VatTu> dcmVT = new DefaultComboBoxModel<>();

    public FormNhapKho() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        tbNhapKho.setModel(dtm);
        tbNhapKho.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbVatTu.setModel(dtmVT);
        tbVatTu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cbxNhanVien.setModel(dcmNV);
        cbxVatTu.setModel(dcmVT);
        hienThiVatTu();
        hienThi();
    }
    
    private void hienThi()
    {
        dtm.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Tên vật tư");
        tieuDe.add("Nhân viên thực hiện");
        tieuDe.add("Thời gian nhập");
        tieuDe.add("Số lượng");
        tieuDe.add("Đơn giá");
        dtm.setColumnIdentifiers(tieuDe);
        
        for (NhapKho nk : getLichSuNK())
        {
            Vector<Object> v = new Vector<>();
            v.add(nk.getVatTu().getTenVT());
            v.add(nk.getNhanVien().getTenNV());
            v.add(nk.getThoiGianNhap());
            v.add(nk.getSoLuongNhap());
            v.add(nk.getDonGiaNhap());
            dtm.addRow(v);
        }
        
        for (NhanVien nv : getDanhSachNV())
        {
            dcmNV.addElement(nv);
        }
        
        for (VatTu vt : getDanhSachVT())
        {
            dcmVT.addElement(vt);
        }
        
        if (tbVatTu.getSelectedRow() >= 0)
        {
            tbVatTuMouseClicked(null);
        }
        else
        {
            hienThiNhapKho(new ArrayList<>());
        }
    }
    
    private void hienThiNhapKho(List<NhapKho> lichSuNhapKho) {
        dtm.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Nhân viên nhập");
        tieuDe.add("Thời gian nhập");
        tieuDe.add("Số lượng");
        tieuDe.add("Đơn giá");
        dtm.setColumnIdentifiers(tieuDe);
        
        for (NhapKho nk : lichSuNhapKho)
        {
            Vector<Object> v = new Vector<>();
            v.add(nk.getNhanVien().getTenNV());
            v.add(nk.getThoiGianNhap());
            v.add(nk.getSoLuongNhap());
            v.add(nk.getDonGiaNhap());
            dtm.addRow(v);
        }
    }
    
    private void hienThiVatTu()
    {
        dtmVT.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Tên vật tư");
        tieuDe.add("Số lượng");
        tieuDe.add("Đơn vị tính");
        tieuDe.add("Đơn giá");
        dtmVT.setColumnIdentifiers(tieuDe);
        
        for (VatTu vt : getDanhSachVT())
        {
            Vector<Object> v = new Vector<>();
            v.add(vt.getTenVT());
            v.add(vt.getSoLuong());
            v.add(vt.getDonViTinh());
            v.add(vt.getDonGia());
            dtmVT.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhapKho = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVatTu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDonGiaNhap = new javax.swing.JTextField();
        cbxNhanVien = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxVatTu = new javax.swing.JComboBox<>();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lịch sử nhập kho"));

        tbNhapKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhapKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhapKho);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách vật tư"));

        tbVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbVatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVatTuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbVatTu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin món ăn"));

        jLabel1.setText("Tên vật tư");
        jLabel1.setToolTipText("");

        jLabel2.setText("Số lượng");

        txtSoLuong.setEditable(false);

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHienThi.setBackground(new java.awt.Color(204, 255, 204));
        btnHienThi.setText("Hiển thị toàn bộ");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        jLabel3.setText("Đơn giá nhập");

        txtDonGiaNhap.setEditable(false);

        jLabel4.setText("Nhân viên thực hiện");
        jLabel4.setToolTipText("");

        txtNgayNhap.setEditable(false);
        txtNgayNhap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy hh:mm:ss"))));

        jLabel5.setText("Ngày nhập");

        btnCapNhat.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 255, 204));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel4)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSoLuong)
                                .addComponent(cbxNhanVien, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxVatTu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNgayNhap)
                                .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(24, 24, 24)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addGap(27, 27, 27)
                        .addComponent(btnHienThi)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxVatTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHienThi)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isEmpty()
    {
        return txtDonGiaNhap.getText().isEmpty() || txtSoLuong.getText().isEmpty();
    }
    
    private boolean isValidValues()
    {
        try {
            int f = Integer.parseInt(txtDonGiaNhap.getText());
            float a = Float.parseFloat(txtSoLuong.getText());
            return true;
        } catch (NumberFormatException e)
        {
            return false;
        }
    }
    
    public void setButtonEditable(boolean value)
    {
        txtDonGiaNhap.setEditable(value);
        txtSoLuong.setEditable(value);
        
        btnCapNhat.setEnabled(!value);
        btnHienThi.setEnabled(!value);
        btnThem.setEnabled(!value);
        btnXoa.setEnabled(!value);
    }
    
    private void tbVatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVatTuMouseClicked
        VatTu vt = getDanhSachVT().get(tbVatTu.getSelectedRow());
        hienThiNhapKho(vt.getLichSuNhapKho());  
        cbxVatTu.setSelectedItem(vt);
    }//GEN-LAST:event_tbVatTuMouseClicked

    private void tbNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhapKhoMouseClicked
        VatTu vt = getDanhSachVT().get(tbVatTu.getSelectedRow());
        NhapKho nk = vt.getLichSuNhapKho().get(tbNhapKho.getSelectedRow());
        cbxNhanVien.setSelectedItem(nk.getNhanVien());
        cbxVatTu.setSelectedItem(vt);
        txtDonGiaNhap.setText("");
        txtDonGiaNhap.setText(String.valueOf(nk.getDonGiaNhap()));
        txtSoLuong.setText("");
        txtSoLuong.setText(String.valueOf(nk.getSoLuongNhap()));
        txtNgayNhap.setText("");
        txtNgayNhap.setText(new SimpleDateFormat("dd/MM/yyyy hh:mm:ss")
                .format(nk.getThoiGianNhap()));
        
        btnThem.setText("Thêm");
        btnCapNhat.setText("Cập nhật");
        setButtonEditable(false);
    }//GEN-LAST:event_tbNhapKhoMouseClicked

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        hienThi();
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (tbNhapKho.getSelectedRow() >= 0)
        {
            if(btnCapNhat.getText().equals("Cập nhật"))
            {
                btnCapNhat.setText("Lưu");
                setButtonEditable(true);
                btnCapNhat.setEnabled(true);
            }
            else if (!isEmpty() && isValidValues())
            {
                VatTu vt = (VatTu) cbxVatTu.getSelectedItem();
                int maNK = vt.getLichSuNhapKho().get(tbNhapKho.getSelectedRow()).getMaNK();
                NhanVien nv = (NhanVien) cbxNhanVien.getSelectedItem();
                int dgn = Integer.parseInt(txtDonGiaNhap.getText());
                float sln = Float.parseFloat(txtSoLuong.getText());
                Timestamp tgn = Timestamp.valueOf(LocalDateTime.now());

                if (XuLyNhapKho.sua(maNK, vt, nv, tgn, dgn, sln))
                {
                    hienThi();
                    hienThiVatTu();
                }

                JOptionPane.showMessageDialog(rootPane, getThongBao());
                btnCapNhat.setText("Cập nhật");
                tbVatTu.setRowSelectionInterval(vt.getMaVT() - 1, vt.getMaVT() - 1);
                tbVatTuMouseClicked(null);
                setButtonEditable(false);
            }
            else
            {
                if (isEmpty())
                {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin nhập khô");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Đợn giá và số lượng phải là số");
                }

                btnCapNhat.setText("Cập nhật");
                setButtonEditable(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thông tin nhập kho cần cập nhật");
        }  
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tbNhapKho.getSelectedRow() >= 0)
        {
            int kq = JOptionPane.showConfirmDialog(
                rootPane, 
                "Bạn có muốn xóa thông tin nhập kho này không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);
        
            if (kq == JOptionPane.YES_OPTION)
            {
                VatTu vt = DanhSach.getDanhSachVT().get(tbVatTu.getSelectedRow());
                int maNK = vt.getLichSuNhapKho().get(
                        tbNhapKho.getSelectedRow()).getMaNK();
                if (XuLyNhapKho.xoa(maNK)) 
                {
                    hienThi();
                    hienThiVatTu();
                }
                
                JOptionPane.showMessageDialog(rootPane, getThongBao());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thông tin nhập kho cần xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(btnThem.getText().equals("Thêm"))
        {
            tbNhapKho.clearSelection();
            txtSoLuong.setText("");
            txtDonGiaNhap.setText("");
            btnThem.setText("Lưu");
            setButtonEditable(true);
            btnThem.setEnabled(true);
        }
        else if (!isEmpty() && isValidValues())
        {
            VatTu vt = (VatTu) cbxVatTu.getSelectedItem();
            NhanVien nv = (NhanVien) cbxNhanVien.getSelectedItem();
            int dgn = Integer.parseInt(txtDonGiaNhap.getText());
            float sln = Float.parseFloat(txtSoLuong.getText());
            Timestamp tgn = Timestamp.valueOf(LocalDateTime.now());
            
            if (XuLyNhapKho.them(vt, nv, tgn, dgn, sln))
            {
                hienThi();
                hienThiVatTu();
            }
            
            JOptionPane.showMessageDialog(rootPane, getThongBao());
            btnThem.setText("Thêm");
            tbVatTu.setRowSelectionInterval(vt.getMaVT() - 1, vt.getMaVT() - 1);
            tbVatTuMouseClicked(null);
            setButtonEditable(false);
        }
        else
        {
            if (isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin nhập khô");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Đợn giá và số lượng phải là số");
            }
            
            btnThem.setText("Thêm");
            setButtonEditable(false);
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<NhanVien> cbxNhanVien;
    private javax.swing.JComboBox<VatTu> cbxVatTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbNhapKho;
    private javax.swing.JTable tbVatTu;
    private javax.swing.JTextField txtDonGiaNhap;
    private javax.swing.JFormattedTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

}
