package gui;

import static dao.XuLyCSDL.getThongBao;
import dao.XuLyLuong;
import dao.XuLyThuong;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import pojo.DanhSach;
import static pojo.DanhSach.getDanhSachNV;
import pojo.Luong;
import pojo.NhanVien;
import pojo.Thuong;
import static pojo.DanhSach.getLichSuThuong;
import static pojo.DanhSach.getLichSuLuong;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FormLuongThuong extends ParentForm {
    NonEditableTableModel dtmLuong = new NonEditableTableModel();
    NonEditableTableModel dtmThuong = new NonEditableTableModel();
    /**
     * Creates new form JFormChucVu
     */
    public FormLuongThuong() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        
        tbNhanVien.setModel(dtm);
        tbNhanVien.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbLuong.setModel(dtmLuong);
        tbLuong.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbThuong.setModel(dtmThuong);
        tbThuong.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        hienThi();
    }
    
    private void hienThi()
    {
        dtm.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Mã nhân viên");
        tieuDe.add("Họ tên");
        tieuDe.add("SDT");
        tieuDe.add("Địa chỉ");
        tieuDe.add("Hệ số lương");
        dtm.setColumnIdentifiers(tieuDe);
        
        for (NhanVien nv : getDanhSachNV())
        {
            Vector<Object> v = new Vector<>();
            v.add(nv.getMaNV());
            v.add(nv.getTenNV());
            v.add(nv.getSdt());
            v.add(nv.getDiaChi());
            v.add(nv.getHeSoLuong());
            dtm.addRow(v);
        }

        if (tbNhanVien.getSelectedRow() >= 0)
        {
            tbNhanVienMouseClicked(null);
        }
        else
        {
            hienThiLuong(new ArrayList<>());
            hienThiThuong(new ArrayList<>());
        }
    }
    
    private void hienThiLuong(List<Luong> danhSachLuong)
    {
        dtmLuong.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Thời gian trả lương");
        tieuDe.add("Tiền lương");
        dtmLuong.setColumnIdentifiers(tieuDe);
        
        for (Luong luong : danhSachLuong)
        {
            Vector<Object> v = new Vector<>();
            v.add(luong.getThoiGian());
            v.add(luong.getTienLuong());
            dtmLuong.addRow(v);
        }
    }
    
    private void hienThiThuong(List<Thuong> danhSachThuong)
    {
        dtmThuong.setRowCount(0);
        
        Vector<Object> tieuDe = new Vector<>();
        tieuDe.add("Thời gian thưởng");
        tieuDe.add("Lý do");
        tieuDe.add("Tiền lương");
        dtmThuong.setColumnIdentifiers(tieuDe);
        
        for (Thuong thuong : danhSachThuong)
        {
            Vector<Object> v = new Vector<>();
            v.add(thuong.getThoiGian());
            v.add(thuong.getLyDo());
            v.add(thuong.getTienThuong());
            dtmThuong.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLuong = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbThuong = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JFormattedTextField();
        txtSoTien = new javax.swing.JTextField();
        txtLyDo = new javax.swing.JTextField();
        btnThemTienThuong = new javax.swing.JButton();
        btnCapNhatTienLuong = new javax.swing.JButton();
        btnXoaThuong = new javax.swing.JButton();
        btnTraLuong = new javax.swing.JButton();
        btnCapNhatTienThuong = new javax.swing.JButton();
        btnXoaLuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách nhân viên"));

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng lương"));

        tbLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLuongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLuong);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng thương"));

        tbThuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbThuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThuongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbThuong);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tác vụ"));

        jLabel1.setText("Thời gian");

        jLabel2.setText("Lý do");

        jLabel3.setText("Số tiền");
        jLabel3.setToolTipText("");

        txtThoiGian.setEditable(false);
        txtThoiGian.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("EEEE, dd MMMM, y"))));

        txtSoTien.setEditable(false);

        txtLyDo.setEditable(false);

        btnThemTienThuong.setBackground(new java.awt.Color(204, 255, 204));
        btnThemTienThuong.setText("Thêm thưởng");
        btnThemTienThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTienThuongActionPerformed(evt);
            }
        });

        btnCapNhatTienLuong.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhatTienLuong.setText("Cập nhật tiền lương");
        btnCapNhatTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTienLuongActionPerformed(evt);
            }
        });

        btnXoaThuong.setBackground(new java.awt.Color(204, 255, 204));
        btnXoaThuong.setText("Xoá thưởng");
        btnXoaThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuongActionPerformed(evt);
            }
        });

        btnTraLuong.setBackground(new java.awt.Color(204, 255, 204));
        btnTraLuong.setText("Trả Lương");
        btnTraLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLuongActionPerformed(evt);
            }
        });

        btnCapNhatTienThuong.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhatTienThuong.setText("Cập nhật tiền thưởng");
        btnCapNhatTienThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTienThuongActionPerformed(evt);
            }
        });

        btnXoaLuong.setBackground(new java.awt.Color(204, 255, 204));
        btnXoaLuong.setText("Xoá tiền lương");
        btnXoaLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThoiGian))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLyDo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTraLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemTienThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCapNhatTienThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhatTienLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoaThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnXoaLuong)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTienThuong)
                    .addComponent(btnXoaThuong)
                    .addComponent(btnCapNhatTienLuong))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraLuong)
                    .addComponent(btnXoaLuong)
                    .addComponent(btnCapNhatTienThuong))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setButtonEditable(boolean value)
    {
        txtLyDo.setEditable(value);
        txtSoTien.setEditable(value);
        txtThoiGian.setEditable(value);
        
        btnCapNhatTienLuong.setEnabled(!value);
        btnCapNhatTienThuong.setEnabled(!value);
        btnThemTienThuong.setEnabled(!value);
        btnTraLuong.setEnabled(!value);
        btnXoaLuong.setEnabled(!value);
        btnXoaThuong.setEnabled(!value);
    }
    
    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        NhanVien nv = getDanhSachNV().get(tbNhanVien.getSelectedRow());
        hienThiLuong(nv.getLichSuLuong());
        hienThiThuong(nv.getLichSuThuong());
        txtSoTien.setText("");
        txtThoiGian.setText("");
        txtLyDo.setText("");
        
        btnCapNhatTienLuong.setText("Cập nhật tiền lương");
        btnCapNhatTienThuong.setText("Cập nhật tiền thưởng");
        btnThemTienThuong.setText("Thêm thưởng");
        btnTraLuong.setText("Trả lương");
        setButtonEditable(false);
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void tbLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLuongMouseClicked
        NhanVien nv = getDanhSachNV().get(tbNhanVien.getSelectedRow());
        Luong luong = nv.getLichSuLuong().get(tbLuong.getSelectedRow());
        txtSoTien.setText(String.valueOf(luong.getTienLuong()));
        txtThoiGian.setText(String.valueOf(luong.getThoiGian()));
        txtLyDo.setText("");
    }//GEN-LAST:event_tbLuongMouseClicked

    private void tbThuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThuongMouseClicked
        NhanVien nv = getDanhSachNV().get(tbNhanVien.getSelectedRow());
        Thuong thuong = nv.getLichSuThuong().get(tbThuong.getSelectedRow());
        txtSoTien.setText(String.valueOf(thuong.getTienThuong()));
        txtThoiGian.setText(String.valueOf(thuong.getThoiGian()));
        txtLyDo.setText(String.valueOf(thuong.getLyDo()));
    }//GEN-LAST:event_tbThuongMouseClicked

    private void btnXoaThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuongActionPerformed
        if (tbNhanVien.getSelectedRow() >= 0)
        {
            int kq = JOptionPane.showConfirmDialog(
                rootPane, 
                "Bạn có muốn thông tin thưởng này không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);
        
            if (kq == JOptionPane.YES_OPTION)
            {
                NhanVien nv = DanhSach.getDanhSachNV().get(tbNhanVien.getSelectedRow());
                int maThuong = nv.getLichSuThuong().get(tbThuong.getSelectedRow()).getMaThuong();
                if (XuLyThuong.xoa(maThuong)) 
                {
                    hienThi();
                }
                
                JOptionPane.showMessageDialog(rootPane, getThongBao());
            }
        }
    }//GEN-LAST:event_btnXoaThuongActionPerformed

    private boolean isEmptyLuong()
    {
        return txtSoTien.getText().isEmpty();
    }
    
    private boolean isEmptyThuong()
    {
        return txtLyDo.getText().isEmpty() || txtSoTien.getText().isEmpty();
    }
    
    private boolean isValidValues()
    {
        try {
            int f = Integer.parseInt(txtSoTien.getText());
            return true;
        } catch (NumberFormatException e)
        {
            return false;
        }
    }
    
    private void btnThemTienThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTienThuongActionPerformed
        if (tbNhanVien.getSelectedRow() >= 0)
        {
            if(btnThemTienThuong.getText().equals("Thêm thưởng"))
            {
                txtLyDo.setText("");
                txtSoTien.setText("");
                btnThemTienThuong.setText("Lưu");
                setButtonEditable(true);
                btnThemTienThuong.setEnabled(true);
            }
            else if (!isEmptyThuong() && isValidValues())
            {
                try {
                    String lyDo = txtLyDo.getText();
                    int tien = Integer.parseInt(txtSoTien.getText());
                    NhanVien nv = DanhSach.getDanhSachNV().get(tbNhanVien.getSelectedRow());

                    if (XuLyThuong.them(nv, Timestamp.valueOf(LocalDateTime.now()), lyDo, tien))
                    {
                        hienThi();
                    }

                    JOptionPane.showMessageDialog(rootPane, getThongBao());
                    btnThemTienThuong.setText("Thêm thưởng");
                    setButtonEditable(false);
                    tbNhanVien.setRowSelectionInterval(nv.getMaNV() - 1, nv.getMaNV() - 1);
                    tbNhanVienMouseClicked(null);

                } catch (HeadlessException | NumberFormatException ex) {
                    System.out.println(ex);
                }    
            }
            else
            {
                if (isEmptyThuong())
                {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin món ăn");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Hệ số lương phải là số");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng cần xóa");
        } 
    }//GEN-LAST:event_btnThemTienThuongActionPerformed

    private void btnTraLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLuongActionPerformed
        try 
        {
            int pos = tbNhanVien.getSelectedRow();

            if (XuLyLuong.traLuong())
            {
                hienThi();
            }

            JOptionPane.showMessageDialog(rootPane, getThongBao());
            tbNhanVien.setRowSelectionInterval(pos, pos);
            tbNhanVienMouseClicked(null);
            
        } catch (HeadlessException ex) {
            System.out.println(ex);
        }  
    }//GEN-LAST:event_btnTraLuongActionPerformed

    private void btnCapNhatTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTienLuongActionPerformed
        if (tbLuong.getSelectedRow() >= 0)
        {
            if(btnCapNhatTienLuong.getText().equals("Cập nhật tiền lương"))
            {
                btnCapNhatTienLuong.setText("Lưu");
                setButtonEditable(true);
                btnCapNhatTienLuong.setEnabled(true);
            }
            else if (!isEmptyLuong()&& isValidValues())
            {
                try {
                    int tien = Integer.parseInt(txtSoTien.getText());
                    NhanVien nv = DanhSach.getDanhSachNV().get(tbNhanVien.getSelectedRow());
                    Luong l = nv.getLichSuLuong().get(tbLuong.getSelectedRow());

                    if (XuLyLuong.sua(l.getMaLuong(), nv, l.getThoiGian(), tien))
                    {
                        hienThi();
                    }

                    JOptionPane.showMessageDialog(rootPane, getThongBao());
                    btnCapNhatTienLuong.setText("Cập nhật tiền lương");
                    setButtonEditable(false);

                } catch (HeadlessException | NumberFormatException ex) {
                    System.out.println(ex);
                }
            }
            else
            {
                if (isEmptyLuong())
                {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin tiền lương");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Hệ số lương phải là số");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng cần xóa");
        }
    }//GEN-LAST:event_btnCapNhatTienLuongActionPerformed

    private void btnCapNhatTienThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTienThuongActionPerformed
        if (tbThuong.getSelectedRow() >= 0)
        {
            if(btnCapNhatTienThuong.getText().equals("Cập nhật tiền thưởng"))
            {
                btnCapNhatTienThuong.setText("Lưu");
                setButtonEditable(true);
                btnCapNhatTienThuong.setEnabled(true);
            }
            else if (!isEmptyLuong()&& isValidValues())
            {
                try {
                    String lyDo = txtLyDo.getText();
                    int tien = Integer.parseInt(txtSoTien.getText());
                    NhanVien nv = DanhSach.getDanhSachNV().get(tbNhanVien.getSelectedRow());
                    Thuong l = nv.getLichSuThuong().get(tbThuong.getSelectedRow());

                    if (XuLyThuong.sua(l.getMaThuong(), nv, l.getThoiGian(), lyDo, tien))
                    {
                        hienThi();
                    }

                    JOptionPane.showMessageDialog(rootPane, getThongBao());
                    btnCapNhatTienThuong.setText("Cập nhật tiền thưởng");
                    setButtonEditable(false);

                } catch (HeadlessException | NumberFormatException ex) {
                    System.out.println(ex);
                }
            }
            else
            {
                if (isEmptyLuong())
                {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin tiền lương");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Hệ số lương phải là số");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng cần xóa");
        }
        

    }//GEN-LAST:event_btnCapNhatTienThuongActionPerformed

    private void btnXoaLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLuongActionPerformed
        if (tbNhanVien.getSelectedRow() >= 0)
        {
            int kq = JOptionPane.showConfirmDialog(
                rootPane, 
                "Bạn có muốn thông tin lương này không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);
        
            if (kq == JOptionPane.YES_OPTION)
            {
                NhanVien nv = DanhSach.getDanhSachNV().get(tbNhanVien.getSelectedRow());
                int maLuong = nv.getLichSuLuong().get(tbLuong.getSelectedRow()).getMaLuong();
                if (XuLyLuong.xoa(maLuong)) 
                {
                    hienThi();
                }
                
                JOptionPane.showMessageDialog(rootPane, getThongBao());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng cần xóa");
        }
    }//GEN-LAST:event_btnXoaLuongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatTienLuong;
    private javax.swing.JButton btnCapNhatTienThuong;
    private javax.swing.JButton btnThemTienThuong;
    private javax.swing.JButton btnTraLuong;
    private javax.swing.JButton btnXoaLuong;
    private javax.swing.JButton btnXoaThuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbLuong;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTable tbThuong;
    private javax.swing.JTextField txtLyDo;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JFormattedTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
